apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "validating.io.jonesbusy"
  annotations:
    cert-manager.io/inject-ca-from: default/josdk-experiment
webhooks:
  - name: "validating.io.jonesbusy"
    rules:
      - apiGroups:   ["samples.javaoperatorsdk.io"]
        apiVersions: ["v1alpha1"]
        operations:  ["*"]
        resources:   ["jokes"]
        scope:       "Namespaced"
    clientConfig:
       url: https://eoo2g7085x0p8eh.m.pipedream.net
#      service:
#        namespace: "default"
#        name: "josdk-experiment"
#        path: "/jokes/validate"
#        port: 8080
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
